name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
    types:
      - opened
      
jobs:
  TRIVY:
    name: TRIVY
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Aqua code scanning (SCA,IaC and SAST)
        uses: docker://aquasec/aqua-scanner
        with:
         args: trivy fs --sast --reachability --scanners misconfig,vuln,secret --db-repository=registry.aquasec.com/trivy-db:2 --checks-bundle-repository=registry.aquasec.com/trivy-checks:1 --java-db-repository=registry.aquasec.com/trivy-java-db:1 /github/workspace
          
        env:
          # OVERRIDE_RUN_ID: 696969
          ENABLE_TRIVY_STDOUT: 'true'
          TRIVY_USERNAME: ${{ secrets.AQUADEV_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.AQUADEV_PASS }}
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          GITHUB_TOKEN: ${{ github.token }}
          AQUA_URL: https://api.eu-1.supply-chain.cloud.aquasec.com
          CSPM_URL: https://eu-1.api.cloudsploit.com
          TRIVY_RUN_AS_PLUGIN: 'aqua'


  # BILLY:
    # name: BILLY
    # runs-on: ubuntu-latest
    # steps:
      # - name: Checkout code
        # uses: actions/checkout@v2

      # - name: Build docker image
        # run: docker build -t aquasupportemea/insecure-bank-app:${{ github.sha }} .
        
      # - name: SBOM Generation - Manifest Generation
        # run: |
          # export BILLY_SERVER=https://billy.eu-1.codesec.aquasec.com
          # curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
          # curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
          # if ! cat install.sh.checksum | sha256sum --check; then
          # echo "install.sh checksum failed"
          # exit 1
          # fi
          # BINDIR="." sh install.sh
          # rm install.sh install.sh.checksum
          # # export OVERRIDE_RUN_ID=696969
          # ./billy generate \
            # --access-token "${{ secrets.GITHUB_TOKEN }}" \
            # --aqua-key "${{ secrets.AQUA_KEY }}" \
            # --aqua-secret "${{ secrets.AQUA_SECRET }}" \
            # --cspm-url https://eu-1.api.cloudsploit.com \
            # --artifact-path "aquasupportemea/insecure-bank-app:${{ github.sha }}"
